package br.metodista.ads.telas;

import br.metodista.ads.modelos.Emprestimo;
import br.metodista.ads.modelos.Livro;
import br.metodista.ads.modelos.Usuario;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Luiz Fernando de Souza ADS - EAD Sorocaba Matricula: 225272
 */
public class Principal extends javax.swing.JFrame {

    private List<Usuario> usuarios = new ArrayList<Usuario>();
    private List<Livro> livros = new ArrayList<Livro>();
    private List<Emprestimo> emprestimos = new ArrayList<Emprestimo>();
    
    public static boolean verificaTelaUsuario;
    public static boolean verificaTelalivro;
    public static boolean verificaTelaEmprestimo;
    public static boolean verificaTelaRelatorio;

    public static void setVerificaTelausuario(boolean verificaTelausuario) {
        Principal.verificaTelaUsuario = verificaTelausuario;
    }

    public static void setVerificaTelalivro(boolean verificaTelalivro) {
        Principal.verificaTelalivro = verificaTelalivro;
    }

    public static void setVerificaTelaEmprestimo(boolean verificaTelaEmprestimo) {
        Principal.verificaTelaEmprestimo = verificaTelaEmprestimo;
    }

    public static void setVerificaTelaRelatorio(boolean verificaTelaRelatorio) {
        Principal.verificaTelaRelatorio = verificaTelaRelatorio;
    }

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        ActionListener tmrHoraAction = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                SimpleDateFormat minhaData =
                        new SimpleDateFormat("dd/MM/yyyy - HH:mm:ss");
                jLabelHora.setText(minhaData.format(new Date()));
            }
        };
        Timer tmrHora = new Timer(1000, tmrHoraAction);
        tmrHora.start();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("books.png")));
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelHora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuItemSubGerenciar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSubItemSair = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuLivro = new javax.swing.JMenu();
        jMenuItemGerenciarLivro = new javax.swing.JMenuItem();
        jMenuItemEmprestarLivro = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuItemListaEmprestimos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Livros");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHora.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 577, Short.MAX_VALUE)
                .addComponent(jLabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jMenuArquivo.setMnemonic('A');
        jMenuArquivo.setText("Arquivo");

        jMenuUsuario.setMnemonic('U');
        jMenuUsuario.setText("Usuário");

        jMenuItemSubGerenciar.setMnemonic('G');
        jMenuItemSubGerenciar.setText("Gerenciar");
        jMenuItemSubGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSubGerenciarActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemSubGerenciar);

        jMenuArquivo.add(jMenuUsuario);
        jMenuArquivo.add(jSeparator2);

        jMenuItemSubItemSair.setMnemonic('S');
        jMenuItemSubItemSair.setText("Sair");
        jMenuItemSubItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSubItemSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemSubItemSair);

        jMenuBar1.add(jMenuArquivo);

        jMenu5.setText("|");
        jMenu5.setEnabled(false);
        jMenuBar1.add(jMenu5);

        jMenuLivro.setMnemonic('L');
        jMenuLivro.setText("Livro");

        jMenuItemGerenciarLivro.setMnemonic('G');
        jMenuItemGerenciarLivro.setText("Gerenciar");
        jMenuItemGerenciarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciarLivroActionPerformed(evt);
            }
        });
        jMenuLivro.add(jMenuItemGerenciarLivro);

        jMenuItemEmprestarLivro.setMnemonic('E');
        jMenuItemEmprestarLivro.setText("Emprestar");
        jMenuItemEmprestarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEmprestarLivroActionPerformed(evt);
            }
        });
        jMenuLivro.add(jMenuItemEmprestarLivro);

        jMenuBar1.add(jMenuLivro);

        jMenu6.setText("|");
        jMenu6.setToolTipText("");
        jMenu6.setEnabled(false);
        jMenuBar1.add(jMenu6);

        jMenuRelatorio.setMnemonic('R');
        jMenuRelatorio.setText("Relatório");

        jMenuItemListaEmprestimos.setMnemonic('L');
        jMenuItemListaEmprestimos.setText("Lista de Emprestimos");
        jMenuItemListaEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaEmprestimosActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuItemListaEmprestimos);

        jMenuBar1.add(jMenuRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        //Alterado o botão padrão para "Não"
        Object[] options = {"Sim", "Não"};

        if (JOptionPane.showOptionDialog(this, "Deseja Sair?", "Atenção",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[1]) == JOptionPane.YES_OPTION) {

            dispose();

        }
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItemSubItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSubItemSairActionPerformed

        formWindowClosing(null);

    }//GEN-LAST:event_jMenuItemSubItemSairActionPerformed

    private void jMenuItemSubGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSubGerenciarActionPerformed

        if (verificaTelaUsuario == false) {
            TelaUsuario telaUsuario = new TelaUsuario();
            jDesktopPane1.remove(telaUsuario);
            jDesktopPane1.add(telaUsuario);
            telaUsuario.setVisible(true);
        }


    }//GEN-LAST:event_jMenuItemSubGerenciarActionPerformed

    private void jMenuItemGerenciarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciarLivroActionPerformed

        if (verificaTelalivro == false) {   

            TelaLivro telaLivro = new TelaLivro();
            jDesktopPane1.remove(telaLivro);
            jDesktopPane1.add(telaLivro);
            telaLivro.setVisible(true);

        }

    }//GEN-LAST:event_jMenuItemGerenciarLivroActionPerformed

    private void jMenuItemEmprestarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEmprestarLivroActionPerformed
        
        if (verificaTelaEmprestimo == false) {   

            TelaEmprestimo telaEmprestimo = new TelaEmprestimo();
            jDesktopPane1.remove(telaEmprestimo);
            jDesktopPane1.add(telaEmprestimo);
            telaEmprestimo.setVisible(true);

        }
    }//GEN-LAST:event_jMenuItemEmprestarLivroActionPerformed

    private void jMenuItemListaEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaEmprestimosActionPerformed
        
        if (verificaTelaRelatorio == false) {   

            RelatorioEmprestimo relatorioEmprestimo = new RelatorioEmprestimo(emprestimos);
            jDesktopPane1.remove(relatorioEmprestimo);
            jDesktopPane1.add(relatorioEmprestimo);
            relatorioEmprestimo.setVisible(true);

        }
        
    }//GEN-LAST:event_jMenuItemListaEmprestimosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private void abrirJanela(JFrame jFrame) {
        //Define a janela como visível. 
        jFrame.setVisible(true);
        //Centraliza a janela no meio da tela. 
        jFrame.setLocationRelativeTo(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemEmprestarLivro;
    private javax.swing.JMenuItem jMenuItemGerenciarLivro;
    private javax.swing.JMenuItem jMenuItemListaEmprestimos;
    private javax.swing.JMenuItem jMenuItemSubGerenciar;
    private javax.swing.JMenuItem jMenuItemSubItemSair;
    private javax.swing.JMenu jMenuLivro;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
