package br.metodista.ads.telas;

import br.metodista.ads.dao.UsuarioDAO;
import br.metodista.ads.modelos.Emprestimo;
import br.metodista.ads.modelos.Livro;
import br.metodista.ads.modelos.Usuario;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Luiz Fernando de Souza ADS - EAD Sorocaba Matricula: 225272
 */
public class TelaEmprestimo extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaEmprestimo
     */
    private Emprestimo emprestimoSelecionado = null;
    private List<Usuario> usuarios;
    private List<Livro> livros;
    private List<Emprestimo> emprestimos;
    private Long[] ids = null;
    int posicao = -1;

    private EmprestimoTableModel emprestimoTableModelo = new EmprestimoTableModel();

    public TelaEmprestimo() {

        try {
            initComponents();
            carregarUsuarios();
        } catch (Exception ex) {
            ex.printStackTrace();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEnmprestimo = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jComboBoxUsuarios = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabelIDUsuario = new javax.swing.JLabel();
        jPanelDadosEmprestimo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmprestimo = new javax.swing.JTable();
        jButtonEmprestar = new javax.swing.JButton();
        jButtonDevolver = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Emprestimo de Livros");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanelEnmprestimo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Emprestimo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanelEnmprestimo.setLayout(null);

        jLabelUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelUsuario.setText("Usuário:");
        jPanelEnmprestimo.add(jLabelUsuario);
        jLabelUsuario.setBounds(150, 30, 58, 17);

        jComboBoxUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxUsuarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBoxUsuarios.setToolTipText("Usuários para Seleção");
        jComboBoxUsuarios.setOpaque(false);
        jComboBoxUsuarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxUsuariosItemStateChanged(evt);
            }
        });
        jPanelEnmprestimo.add(jComboBoxUsuarios);
        jComboBoxUsuarios.setBounds(160, 60, 486, 34);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("ID:");
        jPanelEnmprestimo.add(jLabel1);
        jLabel1.setBounds(30, 30, 18, 17);

        jLabelIDUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jLabelIDUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelIDUsuario.setForeground(new java.awt.Color(255, 0, 0));
        jLabelIDUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIDUsuario.setOpaque(true);
        jPanelEnmprestimo.add(jLabelIDUsuario);
        jLabelIDUsuario.setBounds(20, 60, 130, 30);

        jPanelDadosEmprestimo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanelDadosEmprestimo.setLayout(null);

        jTableEmprestimo.setModel(emprestimoTableModelo);
        jTableEmprestimo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableEmprestimo.getTableHeader().setReorderingAllowed(false);
        jTableEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmprestimoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmprestimo);

        jPanelDadosEmprestimo.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 640, 320);

        jButtonEmprestar.setMnemonic('E');
        jButtonEmprestar.setText("Emprestar");
        jButtonEmprestar.setToolTipText("Alt + E");
        jButtonEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmprestarActionPerformed(evt);
            }
        });

        jButtonDevolver.setMnemonic('D');
        jButtonDevolver.setText("Devolver");
        jButtonDevolver.setToolTipText("Alt + D");
        jButtonDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevolverActionPerformed(evt);
            }
        });

        jButtonAtualizar.setMnemonic('A');
        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.setToolTipText("Alt + A");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonFechar.setMnemonic('F');
        jButtonFechar.setText("Fechar");
        jButtonFechar.setToolTipText("Alt + F");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDadosEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEnmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jButtonEmprestar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEnmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDadosEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEmprestar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButtonFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDevolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmprestarActionPerformed

        Usuario u = new Usuario(Long.parseLong(jLabelIDUsuario.getText()),
                jComboBoxUsuarios.getSelectedItem().toString());

        //Emprestimo e = new Emprestimo(emprestimoSelecionado.getLivro(), u);
        Emprestimo e = new Emprestimo(null, new Date(),
                null, emprestimoSelecionado.getLivro(), u);

        try {

            if (emprestimoSelecionado.getLivro().getEmprestado() != 1) {

                emprestimoTableModelo.emprestar(e, posicao);
                JOptionPane.showMessageDialog(this, "Livro Emprestado",
                        "Emprestimo", JOptionPane.INFORMATION_MESSAGE);
                
                jComboBoxUsuarios.setSelectedIndex(-1);
                jLabelIDUsuario.setText("");
                
            } else {

                JOptionPane.showMessageDialog(this, "Livro Indisponível para Emprestimo!",
                        "Emprestimo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {

            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButtonEmprestarActionPerformed

    private void jButtonDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevolverActionPerformed

        try {

            if (emprestimoSelecionado.getLivro().getEmprestado() == 1) {

                Emprestimo e = new Emprestimo(null, null,
                        new Date(), emprestimoSelecionado.getLivro(), null);

                emprestimoTableModelo.devolver(e);
                
                JOptionPane.showMessageDialog(this, "Livro Devolvido!!!",
                    "Devolução", JOptionPane.INFORMATION_MESSAGE);

            } else {
                
               JOptionPane.showMessageDialog(this, "O livro está disponível!",
                    "Emprestimo", JOptionPane.INFORMATION_MESSAGE); 
            
            }

            }catch (Exception ex) {
            ex.printStackTrace();
        }         


    }//GEN-LAST:event_jButtonDevolverActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        Principal.setVerificaTelaEmprestimo(true);

    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed

        Principal.setVerificaTelaEmprestimo(false);

    }//GEN-LAST:event_formInternalFrameClosed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing

        dispose();

    }//GEN-LAST:event_formInternalFrameClosing

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed

        try {

            carregarUsuarios();
            jLabelIDUsuario.setText("");
            posicao = -1; 
            

        } catch (Exception ex) {

            ex.printStackTrace();
        }


    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed

        dispose();

    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jTableEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmprestimoMouseClicked

        Emprestimo e = emprestimoTableModelo.getEmprestimos(jTableEmprestimo.getSelectedRow());
        emprestimoSelecionado = e;
        posicao = jTableEmprestimo.getSelectedRow();


    }//GEN-LAST:event_jTableEmprestimoMouseClicked

    private void jComboBoxUsuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxUsuariosItemStateChanged

        String idCombo = String.valueOf(ids[jComboBoxUsuarios.getSelectedIndex()]);

        jLabelIDUsuario.setText(idCombo);

    }//GEN-LAST:event_jComboBoxUsuariosItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonDevolver;
    private javax.swing.JButton jButtonEmprestar;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JComboBox<String> jComboBoxUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelIDUsuario;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelDadosEmprestimo;
    private javax.swing.JPanel jPanelEnmprestimo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmprestimo;
    // End of variables declaration//GEN-END:variables

    private void carregarUsuarios() throws Exception {

        try {

            UsuarioDAO dao = new UsuarioDAO();
            usuarios = dao.consultar();

            String[] logins = new String[usuarios.size()];
            ids = new Long[(usuarios.size())];

            for (int cont = 0; cont < usuarios.size(); cont++) {
                logins[cont] = usuarios.get(cont).getLogin();
                ids[cont] = usuarios.get(cont).getId();
            }

            //Cria um combo box com o vetor de logins.
            jComboBoxUsuarios.setModel(new javax.swing.DefaultComboBoxModel(logins));

            jComboBoxUsuarios.setSelectedIndex(-1);

        } catch (Exception e) {

            e.printStackTrace();
        }

    }

}
