package br.metodista.ads.telas;

import br.metodista.ads.modelos.Usuario;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luiz Fernando de Souza ADS - EAD Sorocaba Matricula: 225272
 */
public class TelaUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaUsuario
     */
    private List<Usuario> usuarios = null;

    private int linhaSelecionada = -1;
    Object[] options = {"Sim", "Não"};

    public TelaUsuario(List<Usuario> usuarios) {
        this.usuarios = usuarios;
        initComponents();
        carregarUsuarios();
        desabilitaBotao();
        desabilitaCaixa();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDadosUsuario = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        txtConfirmaSenha = new javax.swing.JPasswordField();
        jLabelNome = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelConfirmaSenha = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jPanelTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro de Usuário");
        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(600, 600));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanelDadosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanelDadosUsuario.setLayout(null);

        txtNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanelDadosUsuario.add(txtNome);
        txtNome.setBounds(20, 50, 490, 30);

        txtUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanelDadosUsuario.add(txtUsuario);
        txtUsuario.setBounds(20, 110, 210, 30);

        txtSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaFocusLost(evt);
            }
        });
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSenhaKeyReleased(evt);
            }
        });
        jPanelDadosUsuario.add(txtSenha);
        txtSenha.setBounds(250, 110, 120, 30);

        txtConfirmaSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanelDadosUsuario.add(txtConfirmaSenha);
        txtConfirmaSenha.setBounds(390, 110, 120, 30);

        jLabelNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNome.setText("Nome:");
        jPanelDadosUsuario.add(jLabelNome);
        jLabelNome.setBounds(10, 30, 50, 17);

        jLabelUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelUsuario.setText("Usuário:");
        jPanelDadosUsuario.add(jLabelUsuario);
        jLabelUsuario.setBounds(10, 90, 70, 17);

        jLabelConfirmaSenha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelConfirmaSenha.setText("Confirmar Senha:");
        jPanelDadosUsuario.add(jLabelConfirmaSenha);
        jLabelConfirmaSenha.setBounds(360, 90, 130, 17);

        jLabelSenha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelSenha.setText("Senha:");
        jPanelDadosUsuario.add(jLabelSenha);
        jLabelSenha.setBounds(240, 90, 48, 17);

        jButtonNovo.setMnemonic('N');
        jButtonNovo.setText("Novo");
        jButtonNovo.setToolTipText("Alt + N");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setMnemonic('S');
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setToolTipText("Alt + S");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonRemover.setMnemonic('R');
        jButtonRemover.setText("Remover");
        jButtonRemover.setToolTipText("Alt + R");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jButtonFechar.setMnemonic('F');
        jButtonFechar.setText("Fechar");
        jButtonFechar.setToolTipText("Alt + F");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jPanelTabela.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanelTabela.setLayout(null);

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome:", "Usuário:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsuarios.setToolTipText("");
        jTableUsuarios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuariosMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableUsuariosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUsuarios);
        if (jTableUsuarios.getColumnModel().getColumnCount() > 0) {
            jTableUsuarios.getColumnModel().getColumn(0).setResizable(false);
            jTableUsuarios.getColumnModel().getColumn(0).setPreferredWidth(350);
            jTableUsuarios.getColumnModel().getColumn(1).setResizable(false);
            jTableUsuarios.getColumnModel().getColumn(1).setPreferredWidth(180);
        }

        jPanelTabela.add(jScrollPane1);
        jScrollPane1.setBounds(5, 24, 546, 247);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelDadosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                            .addComponent(jPanelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanelDadosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonRemover)
                    .addComponent(jButtonFechar))
                .addGap(18, 18, 18)
                .addComponent(jPanelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing

        dispose();

    }//GEN-LAST:event_formInternalFrameClosing

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        String senha = Arrays.toString(txtSenha.getPassword());
        String confirmaSenha = Arrays.toString(txtConfirmaSenha.getPassword());
        
        
        if ("".equals(txtNome.getText())) {

            JOptionPane.showMessageDialog(this, "Nome é Obrigatório!!",
                    "Aviso", JOptionPane.OK_OPTION);
            txtNome.requestFocus();
        } else if ("".equals(txtUsuario.getText())) {

            JOptionPane.showMessageDialog(this, "Usuario é Obrigatório!",
                    "Erro", JOptionPane.OK_OPTION);
            txtUsuario.requestFocus();

        } else if (!senha.equals(confirmaSenha)) {

            JOptionPane.showMessageDialog(this, "Digite a mesma senha para Confirmação, verifique CAPSLOCK!",
                    "Erro", JOptionPane.OK_OPTION);
            txtConfirmaSenha.setText("");
            txtSenha.setText("");
            txtSenha.requestFocus();

        } else {

            Usuario u = obterUsuario(usuarios, txtUsuario.getText());

            if (u == null) {

                u = new Usuario();
                u.setNome(txtNome.getText());
                u.setLogin(txtUsuario.getText());
                u.setSenha(new String(txtSenha.getPassword()));

                usuarios.add(u);
            } else {

                u.setNome(txtNome.getText());
                u.setSenha(new String(txtSenha.getPassword()));
            }
            carregarUsuarios();
            limparDados();

        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed

        limparDados();
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);

    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jTableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuariosMouseClicked

        linhaSelecionada = jTableUsuarios.getSelectedRow();
        Usuario u = usuarios.get(linhaSelecionada);
        preencherDadosUsuario(u);
        jButtonRemover.setEnabled(true);
        habilitaCaixa();
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(true);


    }//GEN-LAST:event_jTableUsuariosMouseClicked

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed

        if (linhaSelecionada != -1) {
            if (JOptionPane.showOptionDialog(this, "Deseja Excluir o Registro?", "Exclusão",
                    JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[1]) == JOptionPane.YES_OPTION) {

                usuarios.remove(linhaSelecionada);
                ((DefaultTableModel) jTableUsuarios.getModel()).removeRow(linhaSelecionada);
                limparDados();
                desabilitaBotao();
                desabilitaCaixa();
                jButtonNovo.setEnabled(true);

            } else {

                JOptionPane.showMessageDialog(this, "Cancelado!!!", "Exclusão", JOptionPane.OK_OPTION);

            }
        } else {

            JOptionPane.showMessageDialog(this, "Selecione um registro para Excluir!", "Exclusão", JOptionPane.OK_OPTION);

        }


    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed

        formInternalFrameClosing(null);

    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jTableUsuariosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuariosMouseReleased

        limparDados();
        desabilitaBotao();
        desabilitaCaixa();

    }//GEN-LAST:event_jTableUsuariosMouseReleased

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        Principal.setVerificaTelausuario(true);

    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed

        Principal.setVerificaTelausuario(false);

    }//GEN-LAST:event_formInternalFrameClosed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed

        habilitaConfirmaSenha();

    }//GEN-LAST:event_txtSenhaKeyPressed

    private void txtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusLost

        habilitaConfirmaSenha();

    }//GEN-LAST:event_txtSenhaFocusLost

    private void txtSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyReleased

        habilitaConfirmaSenha();

    }//GEN-LAST:event_txtSenhaKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelConfirmaSenha;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelDadosUsuario;
    private javax.swing.JPanel jPanelTabela;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JPasswordField txtConfirmaSenha;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void carregarUsuarios() {

        for (int cont = jTableUsuarios.getRowCount() - 1; cont >= 0; cont--) {

            ((DefaultTableModel) jTableUsuarios.getModel()).removeRow(cont);

        }

        for (Usuario u : usuarios) {

            ((DefaultTableModel) jTableUsuarios.getModel()).addRow(u.carregarGrid());

        }
    }

    private Usuario obterUsuario(List<Usuario> usuarios, String login) {

        Usuario usuario = null;

        for (Usuario u : usuarios) {

            if (u.getLogin().equals(login)) {

                usuario = u;
                break;

            }
        }

        return usuario;
    }

    private void limparDados() {

        this.txtNome.setText("");
        this.txtUsuario.setText("");
        this.txtSenha.setText("");
        this.txtConfirmaSenha.setText("");
        this.txtNome.requestFocus();
        this.linhaSelecionada = -1;
        this.txtNome.setEnabled(true);
        this.txtUsuario.setEnabled(true);
        this.txtSenha.setEnabled(true);

    }

    private void habilitaBotao() {

        this.jButtonRemover.setEnabled(true);
        this.jButtonSalvar.setEnabled(true);
    }

    private void desabilitaBotao() {

        this.jButtonRemover.setEnabled(false);
        this.jButtonSalvar.setEnabled(false);

    }

    private void habilitaCaixa() {

        this.txtNome.setEnabled(true);
        this.txtUsuario.setEnabled(true);
        this.txtSenha.setEnabled(true);

    }

    private void desabilitaCaixa() {

        this.txtNome.setEnabled(false);
        this.txtUsuario.setEnabled(false);
        this.txtSenha.setEnabled(false);
        this.txtConfirmaSenha.setEnabled(false);
    }

    private void preencherDadosUsuario(Usuario u) {

        this.txtNome.setText(u.getNome());
        this.txtUsuario.setText(u.getLogin());
        this.txtSenha.setText(u.getSenha());

    }

    private void habilitaConfirmaSenha() {

        if (txtSenha.getPassword().length >= 3) {

            txtConfirmaSenha.setEnabled(true);

        } else {

            txtConfirmaSenha.setEnabled(false);

        }
    }

}
